### ISSUE TITLE
Do you really need the UI for the Transfer Subs script?

### ISSUE THREAD

**Issue by schriftgestalt** [jpt/font-scripts#4]
https://github.com/jpt/font-scripts/blob/a7c613df53638490f478434a18c6d0f9866090d3/Glyphs/Transfer%20OT%20subs%20to%20static%20instances.py#L26

You could go through all features and look for `condition`?

**Comment by jpt** [comment]
Hmm, that's a good point, I can take a look at doing it this way.  I wonder if there would be any edge cases

**Comment by schriftgestalt** [comment]
normally, all condition should be in one feature. I would show an error alert when you find them in two different ones.

**Comment by jpt** [comment]
ok, this should work: https://github.com/jpt/font-scripts/commit/3086f2cf0d43e634b05796ec0a0cee1968cdca96
thank you, georg
